name: docs
on: gollum
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Push wiki changes
      run: |
        cd docs
        git reset --hard origin/master
        git pull origin master
        git config --local user.name "${{git show --format='%aN' --quiet}}"
        git config --local user.email "${{git show --format='%aE' --quiet}}"
        cd ..
        git add .
        git diff-index --quiet HEAD || git commit -m "${{git log -1  --pretty='%s'}}" && git push
