name: docs
on: gollum
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Push wiki changes
      run: |
        cd docs
        git reset --hard origin/master
        git pull origin master
        GIT_USER=`git show --format='%aN' --quiet`
        GIT_EMAIL=`git show --format='%aE' --quiet`
        GIT_COMMIT=`git log -1  --pretty='%s'`
        echo "$GIT_USER $GIT_EMAIL $GIT_COMMIT"
        git config --local user.name "${{env.GIT_USER}}"
        git config --local user.email "${{env.GIT_EMAIL}}"
        cd ..
        git add .
        git diff-index --quiet HEAD || git commit -m "${{env.GIT_COMMIT}}" && git push
